# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'millennial-3'

menu:
- {name: 'Blogs', folder: 'pages', file: 'documentation/index.html'}
- {name: 'Tags', folder: 'pages', file: 'tags/index.html'}
- {name: 'Gallery', folder: 'pages', file: 'facts/index.html'}
- {name: 'About', folder: 'pages', file: 'about/index.html'}
- {name: 'Pending', folder: 'pages', file: 'resources/index.html'}
#- {name: '可以请别联系我', folder: 'pages', file: 'contact/index.html'}

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
#- {icon: 'weibo', link: 'https://twitter.com/paululele'}
#- {icon: 'user', link: 'https://www.facebook.com/Le.Paul.94'}
- {icon: 'instagram', link: 'https://instagram.com/paululele',desc：''}
- {icon: 'envelope', link: 'mailto:jsymsong@gmail.com',desc：''}
# - {icon: 'rss-square', link: 'rss-feed.xml'}

#include file dir
include_dir: '/assets/_includes'
# Customize site text
pagination:
  next_page: 'Newer'
  previous_page: 'Older'

sharing_button_prompt: 'sharing:'

related_posts: '你说的都对'

post_date_prefix: '正在憋。。。'
